const express = require('express')
const cors = require('cors')
const app = express()
const port = 3000
app.use(cors())
app.use(express.json())

const db = require('./config/db')
const BeedJewellary = require('./routes/BeedJewellaryRoute')
const Users = require('./routes/UserRoute')
const Auth = require('./routes/AuthRoute')
const FashionJewellary = require('./routes/FashionJewellaryRoute')
const PendantJewellary = require('./routes/PendantJewellaryRoute')
const WeddingJewellary = require('./routes/WeddingJewellaryRoute')
app.get('/', (req, res) => res.status(200).json({ message: "Welcome" }))
app.use('/BeedJewellary', BeedJewellary)
app.use('/FashionJewellary', FashionJewellary)
app.use('/PendantJewellary', PendantJewellary)
app.use('/WeddingJewellary', WeddingJewellary)
app.use('/users', Users)
app.use('/auth', Auth)

app.listen(port, (() => console.log(`Listening on ${port}`)))